# Site settings
title: 名词王国
header-img: "img/green.jpg"
tagline: "cn"  
description: "任如意|理性·自由"  
baseurl: ""
url: "http://dittoyi.github.io"  

# About/contact
owner: 
  name: " Dittoyi"
  email: ruyi.ren@yahoo.com
  bio: "理性·自由"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  dittoyi
twitter_username: dittoyi
github_username: dittoyi
facebook_username: dittoyi
weibo_username: dittoyi 
zhihu_username: ren-dittoyi

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CnFeat"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : dittoyi
  disqus :
      short_name : dittoyi

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation